apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rust-grrs
  description: Rust CLI tool to search for a string in a file and display the lines that contain it
  links:
    - url: https://github.com/Parsifal-M/rust-grrs
      title: Repository
      icon: github
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: Service
  owner: Peter Macdonald
  lifecycle: Sandbox